export default {
    kind: "customsearch#search",
    url: {
        type: "application/json",
        template: "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
    },
    queries: {
        request: [{
            title: "Google Custom Search - hello eo",
            totalResults: "36900",
            searchTerms: "hello eo",
            count: 10,
            startIndex: 1,
            inputEncoding: "utf8",
            outputEncoding: "utf8",
            safe: "off",
            cx: "dfadafe74bd94e4ba",
        }, ],
        nextPage: [{
            title: "Google Custom Search - hello eo",
            totalResults: "36900",
            searchTerms: "hello eo",
            count: 10,
            startIndex: 11,
            inputEncoding: "utf8",
            outputEncoding: "utf8",
            safe: "off",
            cx: "dfadafe74bd94e4ba",
        }, ],
    },
    context: {
        title: "Google",
    },
    searchInformation: {
        searchTime: 0.407559,
        formattedSearchTime: "0.41",
        totalResults: "36900",
        formattedTotalResults: "36,900",
    },
    items: [{
            kind: "customsearch#result",
            title: "Google",
            htmlTitle: "Google",
            link: "https://www.google.com/imghp?hl=EN",
            displayLink: "www.google.com",
            snippet: "Google Images. The most comprehensive image search on the web.",
            htmlSnippet: "Google Images. The most comprehensive image search on the web.",
            cacheId: "ZY5ouBM3GeMJ",
            formattedUrl: "https://www.google.com/imghp?hl=EN",
            htmlFormattedUrl: "https://www.google.com/imghp?hl=EN",
            pagemap: {
                metatags: [{
                    referrer: "origin",
                    viewport: "width=device-width,minimum-scale=1.0",
                    google: "notranslate",
                    "format-detection": "telephone=no",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Maps",
            htmlTitle: "Google Maps",
            link: "https://www.google.com/maps/contrib/106669480032717095863/reviews",
            displayLink: "www.google.com",
            snippet: "E. O. ; Photo of Milton District Hospital Emergency Room. Milton District Hospital Emergency Room. 725 Bronte St S, Milton, ON L9T 9K1, Canada ; Photo of CIBC ...",
            htmlSnippet: "<b>E. O.</b> ; Photo of Milton District Hospital Emergency Room. Milton District Hospital Emergency Room. 725 Bronte St S, Milton, ON L9T 9K1, Canada ; Photo of CIBC&nbsp;...",
            cacheId: "HvubKGndpNsJ",
            formattedUrl: "https://www.google.com/maps/contrib/106669480032717095863/reviews",
            htmlFormattedUrl: "https://www.google.com/maps/contrib/106669480032717095863/reviews",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSnvOWa__nknQDPhRK3biydCez_GcRd6HdMu0Y6vHm6pF4ps-rQyn4wCEiB",
                    width: "310",
                    height: "163",
                }, ],
                metatags: [{
                    referrer: "origin",
                    "og:image": "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_3.png",
                    "og:image:width": "256",
                    "twitter:card": "summary",
                    "og:site_name": "Contributions by E. O.",
                    viewport: "initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no",
                    "og:title": "Contributions by E. O.",
                    "og:image:height": "256",
                    google: "notranslate",
                    "og:description": "Level 3 Local Guide | 116 Points",
                }, ],
                place: [{
                    image: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_3.png",
                    name: "Contributions by E. O.",
                    description: "Level 3 Local Guide | 116 Points",
                }, ],
                cse_image: [{
                    src: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_3.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Maps",
            htmlTitle: "Google Maps",
            link: "https://www.google.com/maps/contrib/106276164531649929395/reviews",
            displayLink: "www.google.com",
            snippet: "(Translated by Google) Hello Edson, you can send your budget to Whatsapp (43) 9-8455-2356, ... Possua em mãos o ano de fabricação e o modelo de seu veículo.",
            htmlSnippet: "(Translated by Google) <b>Hello</b> Edson, you can send your budget to Whatsapp (43) 9-8455-2356, ... Possua em mãos o ano de fabricação <b>e o</b> modelo de seu veículo.",
            cacheId: "ZcxI1ogaVXEJ",
            formattedUrl: "https://www.google.com/maps/contrib/106276164531649929395/reviews",
            htmlFormattedUrl: "https://www.google.com/maps/contrib/106276164531649929395/reviews",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSjsuMXw41HvKt-V5343CUF8T9SctSxlub6gOjFnmpdNLm0us0e5clNujI",
                    width: "310",
                    height: "163",
                }, ],
                metatags: [{
                    referrer: "origin",
                    "og:image": "https://maps.gstatic.com/tactile/geoprofile/sharing/non_lg.png",
                    "og:image:width": "256",
                    "twitter:card": "summary",
                    "og:site_name": "Contributions by Edson Junior",
                    viewport: "initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no",
                    "og:title": "Contributions by Edson Junior",
                    "og:image:height": "256",
                    google: "notranslate",
                    "og:description": "11 Contributions",
                }, ],
                place: [{
                    image: "https://maps.gstatic.com/tactile/geoprofile/sharing/non_lg.png",
                    name: "Contributions by Edson Junior",
                    description: "11 Contributions",
                }, ],
                cse_image: [{
                    src: "https://maps.gstatic.com/tactile/geoprofile/sharing/non_lg.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google",
            htmlTitle: "Google",
            link: "https://www.google.com/",
            displayLink: "www.google.com",
            snippet: "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking ...",
            htmlSnippet: "Search the world&#39;s information, including webpages, images, videos and more. Google has many special features to help you find exactly what you&#39;re looking&nbsp;...",
            cacheId: "y14FcUQOGl4J",
            formattedUrl: "https://www.google.com/",
            htmlFormattedUrl: "https://www.google.com/",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT3X9ZpkcNrr2kAcGZuXPZTNiK1oeTXhRMCZ1UGxNLf-an4du0eriX01mc",
                    width: "320",
                    height: "112",
                }, ],
                metatags: [{
                    referrer: "origin",
                    viewport: "width=device-width,minimum-scale=1.0",
                    google: "notranslate",
                    "format-detection": "telephone=no",
                }, ],
                cse_image: [{
                    src: "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Maps",
            htmlTitle: "Google Maps",
            link: "https://www.google.com/maps/contrib/102579673582013535309/reviews",
            displayLink: "www.google.com",
            snippet: "Que lugar maravilhoso, comida muito boa e o melhor benefício da Bahia, com um mar bem agitado, mas delicioso de tomar ... (Translated by Google) Hello Jose.",
            htmlSnippet: "Que lugar maravilhoso, comida muito boa <b>e o</b> melhor benefício da Bahia, com um mar bem agitado, mas delicioso de tomar ... (Translated by Google) <b>Hello</b> Jose.",
            cacheId: "V_B7dOGFy_cJ",
            formattedUrl: "https://www.google.com/maps/contrib/102579673582013535309/reviews",
            htmlFormattedUrl: "https://www.google.com/maps/contrib/102579673582013535309/reviews",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS6AKPxcKCbFW7eGHGdTjCiqmdQQ5IgvK--21nWN8kIjF239s-qTIZ3Jk8T",
                    width: "310",
                    height: "163",
                }, ],
                metatags: [{
                    referrer: "origin",
                    "og:image": "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                    "og:image:width": "256",
                    "twitter:card": "summary",
                    "og:site_name": "Contributions by José Gustavo",
                    viewport: "initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no",
                    "og:title": "Contributions by José Gustavo",
                    "og:image:height": "256",
                    google: "notranslate",
                    "og:description": "Level 7 Local Guide | 9,922 Points",
                }, ],
                place: [{
                    image: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                    name: "Contributions by José Gustavo",
                    description: "Level 7 Local Guide | 9,922 Points",
                }, ],
                cse_image: [{
                    src: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Maps",
            htmlTitle: "Google Maps",
            link: "https://www.google.com/maps/contrib/103205788170026960035/reviews",
            displayLink: "www.google.com",
            snippet: "VID EO ; Photo of Electroplanet, Electroménager, TV, Hifi, Multimédia, audio et jeux vidéo. Electroplanet, Electroménager, TV, Hifi, Multimédia, audio et jeux ...",
            htmlSnippet: "VID <b>EO</b> ; Photo of Electroplanet, Electroménager, TV, Hifi, Multimédia, audio et jeux vidéo. Electroplanet, Electroménager, TV, Hifi, Multimédia, audio et jeux&nbsp;...",
            cacheId: "NtfVNT_xb0oJ",
            formattedUrl: "https://www.google.com/maps/contrib/103205788170026960035/reviews",
            htmlFormattedUrl: "https://www.google.com/maps/contrib/103205788170026960035/reviews",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS6AKPxcKCbFW7eGHGdTjCiqmdQQ5IgvK--21nWN8kIjF239s-qTIZ3Jk8T",
                    width: "310",
                    height: "163",
                }, ],
                metatags: [{
                    referrer: "origin",
                    "og:image": "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                    "og:image:width": "256",
                    "twitter:card": "summary",
                    "og:site_name": "Contributions by VID EO",
                    viewport: "initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no",
                    "og:title": "Contributions by VID EO",
                    "og:image:height": "256",
                    google: "notranslate",
                    "og:description": "Level 6 Local Guide | 2,642 Points",
                }, ],
                place: [{
                    image: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                    name: "Contributions by VID EO",
                    description: "Level 6 Local Guide | 2,642 Points",
                }, ],
                cse_image: [{
                    src: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Maps",
            htmlTitle: "Google Maps",
            link: "https://www.google.com/maps/contrib/104391583338659112089/reviews",
            displayLink: "www.google.com",
            snippet: "EO Thasou Limenarion, Thasos 640 10, Greece -. 3 months ago ... Hello, deejayflavio! Thank you for your feedback. In order to verify and improve the ...",
            htmlSnippet: "<b>EO</b> Thasou Limenarion, Thasos 640 10, Greece -. 3 months ago ... <b>Hello</b>, deejayflavio! Thank you for your feedback. In order to verify and improve the&nbsp;...",
            cacheId: "y_IXOQK4tAgJ",
            formattedUrl: "https://www.google.com/maps/contrib/104391583338659112089/reviews",
            htmlFormattedUrl: "https://www.google.com/maps/contrib/104391583338659112089/reviews",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS6AKPxcKCbFW7eGHGdTjCiqmdQQ5IgvK--21nWN8kIjF239s-qTIZ3Jk8T",
                    width: "310",
                    height: "163",
                }, ],
                metatags: [{
                    referrer: "origin",
                    "og:image": "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                    "og:image:width": "256",
                    "twitter:card": "summary",
                    "og:site_name": "Contributions by deejayflavio",
                    viewport: "initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no",
                    "og:title": "Contributions by deejayflavio",
                    "og:image:height": "256",
                    google: "notranslate",
                    "og:description": "Level 8 Local Guide | 19,710 Points",
                }, ],
                place: [{
                    image: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                    name: "Contributions by deejayflavio",
                    description: "Level 8 Local Guide | 19,710 Points",
                }, ],
                cse_image: [{
                    src: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Google Maps",
            htmlTitle: "Google Maps",
            link: "https://www.google.com/maps/contrib/118286653280331382514/reviews",
            displayLink: "www.google.com",
            snippet: "(Translated by Google) Hello, thank you for your feedback. ... Palea EO Irakliou Agiou Nikolaou 25. km, Chersonisos 700 14, Greece -. 2 years ago.",
            htmlSnippet: "(Translated by Google) <b>Hello</b>, thank you for your feedback. ... Palea <b>EO</b> Irakliou Agiou Nikolaou 25. km, Chersonisos 700 14, Greece -. 2 years ago.",
            cacheId: "C8qQ-sKxMP0J",
            formattedUrl: "https://www.google.com/maps/contrib/118286653280331382514/reviews",
            htmlFormattedUrl: "https://www.google.com/maps/contrib/118286653280331382514/reviews",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS6AKPxcKCbFW7eGHGdTjCiqmdQQ5IgvK--21nWN8kIjF239s-qTIZ3Jk8T",
                    width: "310",
                    height: "163",
                }, ],
                metatags: [{
                    referrer: "origin",
                    "og:image": "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                    "og:image:width": "256",
                    "twitter:card": "summary",
                    "og:site_name": "Contributions by Kirill Flerov",
                    viewport: "initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no",
                    "og:title": "Contributions by Kirill Flerov",
                    "og:image:height": "256",
                    google: "notranslate",
                    "og:description": "Level 7 Local Guide | 8,223 Points",
                }, ],
                place: [{
                    image: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                    name: "Contributions by Kirill Flerov",
                    description: "Level 7 Local Guide | 8,223 Points",
                }, ],
                cse_image: [{
                    src: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_5.png",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Ruma Andina by DECK",
            htmlTitle: "Ruma Andina by DECK",
            link: "https://www.google.com/travel/hotels/entity/CgoIrbq73cKm3PgmEAE?g2lb=2502548,2503770,2503781,4258168,4306835,4317915,4328159,4371334,4401769,4419364,4463666,4482194,4482438,4486153,4491349,4495816,4496891,4270859,4284970&hl=en&gl&un=1&grf=EmQKLAgOEigSJnIkKiIKBwjlDxADGAQSBwjlDxADGAUgADAeQMoCSgcI5Q8QAhgPCjQIDBIwEi6yASsSKQonCiUweDk2MTBiZjE2ZTlkZGUyNTc6MHhkNzc0YmNjYWVkMjk1NWVm&rp=EO-rpemuma-61wE4AkAASAHAAQI&ictx=1&ei=cjQrYORYxK6VBs3grfgC&sa=X&ei=CF8VYvWrJIyw2gKC-6H4Cg&ved=2ahUKEwj1z-PKqZT2AhUMmFYKHYJ9CK8QkP8FegUIARCjAQ",
            displayLink: "www.google.com",
            snippet: "(Translated by Google) Hello Gabriela! How are you!? Thank you very much for leaving us your opinion, it is always important to be in the details to improve ...",
            htmlSnippet: "(Translated by Google) <b>Hello</b> Gabriela! How are you!? Thank you very much for leaving us your opinion, it is always important to be in the details to improve&nbsp;...",
            formattedUrl: "https://www.google.com/.../CgoIrbq73cKm3PgmEAE?...EO...",
            htmlFormattedUrl: "https://www.google.com/.../CgoIrbq73cKm3PgmEAE?...<b>EO</b>...",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS8pjyPybg2IaXZDyHqhOT9IMAU9uZLp7HqOmweb4GAFUqNPGETzrOigTuF",
                    width: "272",
                    height: "185",
                }, ],
                metatags: [{
                    "application-name": "Travel",
                    "og:image": "https://lh5.googleusercontent.com/p/AF1QipNyaO0HdqDswJUev6wuTFzOGqGUlmB_FCl8sHoD=w296-h202-n-k-no-v1",
                    "og:type": "website",
                    "og:image:width": "296",
                    "twitter:card": "summary_large_image",
                    "twitter:title": "Ruma Andina by DECK 4.4 ★ (385)",
                    mod: "true",
                    "og:site_name": "Google Hotel Search",
                    "apple-mobile-web-app-title": "Travel",
                    "og:title": "Ruma Andina by DECK 4.4 ★ (385)",
                    "og:image:height": "202",
                    "og:description": "$129 · Mar 11–12",
                    "twitter:image": "https://lh5.googleusercontent.com/p/AF1QipNyaO0HdqDswJUev6wuTFzOGqGUlmB_FCl8sHoD=w296-h202-n-k-no-v1",
                    referrer: "origin",
                    "twitter:image:alt": "Ruma Andina by DECK 4.4 ★ (385)",
                    "apple-mobile-web-app-status-bar-style": "black",
                    "msapplication-tap-highlight": "no",
                    viewport: "width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no",
                    "apple-mobile-web-app-capable": "yes",
                    "twitter:description": "$129 · Mar 11–12",
                    "mobile-web-app-capable": "yes",
                    "og:locale": "en",
                    "og:url": "https://www.google.com/travel/hotels/entity/ChcIrbq73cKm3PgmGgsvZy8xdGdxN3Z4eBAB?g2lb=4356900",
                }, ],
                cse_image: [{
                    src: "https://lh5.googleusercontent.com/p/AF1QipNyaO0HdqDswJUev6wuTFzOGqGUlmB_FCl8sHoD=w296-h202-n-k-no-v1",
                }, ],
            },
        },
        {
            kind: "customsearch#result",
            title: "Hello Comandatuba",
            htmlTitle: "<b>Hello</b> Comandatuba",
            link: "https://www.google.com/travel/hotels/entity/CgoIvLy-k9mkl_V9EAE?ei=pMsWYv-uFsPBlQaG0I-wBQ&sa=X&ved=2ahUKEwj_kNOmhZf2AhXDYMUKHQboA1YQkP8FegUIARCAAQ",
            displayLink: "www.google.com",
            snippet: "Popular hotels · Similar to Hello Comandatuba · Google review summary · People often mention · Rooms · Location · About this hotel · Photos.",
            htmlSnippet: "Popular hotels &middot; Similar to <b>Hello</b> Comandatuba &middot; Google review summary &middot; People often mention &middot; Rooms &middot; Location &middot; About this hotel &middot; Photos.",
            cacheId: "lahVAQkESBoJ",
            formattedUrl: "https://www.google.com/travel/hotels/.../CgoIvLy-k9mkl_V9EAE?...",
            htmlFormattedUrl: "https://www.google.com/travel/hotels/.../CgoIvLy-k9mkl_V9EAE?...",
            pagemap: {
                cse_thumbnail: [{
                    src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTMpaaAhi1hWWVaZyJsLs95Ydr_wxqQRWpfdhfZMzi6hUrdodkKKlk-6pxE",
                    width: "272",
                    height: "185",
                }, ],
                metatags: [{
                    "application-name": "Travel",
                    "og:image": "https://lh5.googleusercontent.com/p/AF1QipPuLECYvGA3Ju1fNfgVwhSEaBSIJPulzlgvgZKP=w296-h202-n-k-no-v1",
                    "og:type": "website",
                    "og:image:width": "296",
                    "twitter:card": "summary_large_image",
                    "twitter:title": "Hello Comandatuba 4.3 ★ (13)",
                    mod: "true",
                    "og:site_name": "Google Hotel Search",
                    "apple-mobile-web-app-title": "Travel",
                    "og:title": "Hello Comandatuba 4.3 ★ (13)",
                    "og:image:height": "202",
                    "twitter:image": "https://lh5.googleusercontent.com/p/AF1QipPuLECYvGA3Ju1fNfgVwhSEaBSIJPulzlgvgZKP=w296-h202-n-k-no-v1",
                    referrer: "origin",
                    "twitter:image:alt": "Hello Comandatuba 4.3 ★ (13)",
                    "apple-mobile-web-app-status-bar-style": "black",
                    "msapplication-tap-highlight": "no",
                    viewport: "width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no",
                    "apple-mobile-web-app-capable": "yes",
                    "mobile-web-app-capable": "yes",
                    "og:locale": "en_US",
                    "og:url": "https://www.google.com/travel/hotels/entity/ChkIvLy-k9mkl_V9Gg0vZy8xMWZtYmQyNnh4EAE?g2lb=4356900",
                }, ],
                cse_image: [{
                    src: "https://lh5.googleusercontent.com/p/AF1QipPuLECYvGA3Ju1fNfgVwhSEaBSIJPulzlgvgZKP=w296-h202-n-k-no-v1",
                }, ],
            },
        },
    ],
};